###############################################################################
# General settings                                         
###############################################################################

[default.logs]
level  = "INFO"
format = "[%(asctime)s] %(levelname)-8s %(name)s: %(message)s"

[default.bot]
parse_mode = "HTML"

###############################################################################
# Development settings                                         
###############################################################################

[development.logs]
# переопределяем только уровень и формат
level  = "DEBUG"
format = "[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d › %(message)s"

###############################################################################
# Production settings                                         
###############################################################################

[production.logs]
    level  = "WARNING"
    format = "[%(asctime)s] [%(levelname)s] %(message)s"
